---
title: "Cross Repo Git Commit History"
output: html_document
---

*****************

```{bash echo=FALSE}
TMPLOG=$(pwd)/tmp-project-log.csv
echo "project,timestamp,message" > $TMPLOG
curdir=$(pwd)
cd ..
for i in *
do
   if [ -d $i ] && [ -d $i/.git ]
   then
      cd $i
      git log --since='1 year ago' --author="$(git config --get user.name)" --pretty=format:"$i,%ai,\"%s\"" >> $TMPLOG
      echo "" >> $TMPLOG
      cd ..
   fi
done
cd $curdir
grep . $TMPLOG > project-logs.csv
rm $TMPLOG
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(data.table)
library(spacyr)
library(tagcloud)
library(ggplot2)
library(scales)

# read in git logs and convert timestamp to workable date and time fields
commit_dt = fread(paste0(getwd(), '/project-logs.csv'))
commit_dt[,timestamp := as.POSIXct(timestamp)]
commit_dt[,date := as.Date(timestamp)]
commit_dt[,time := as.POSIXct(format(timestamp, '%H:%M:%S'), format='%H:%M:%S')]

# count commits per repo
repo_commit_count_dt = commit_dt[, .N, by=project][order(-N), ]

# make project a factor with levels orderd by commit count (large to small)
repo_commit_count_dt[, project := factor(project, rev(project))]
commit_dt[, project := factor(project, repo_commit_count_dt$project)]

# take only top 10 repos by commit count for barplot
repo_commit_count_dt = repo_commit_count_dt[1:min(20, .N),]

# plot commits by date/time
date_time_plot = ggplot(commit_dt[project %in% repo_commit_count_dt$project], 
                        aes(x=date, y=time, color=project)) +
  geom_point() +
  scale_y_datetime(labels = date_format('%H:%M')) +
  scale_x_date(labels = date_format('%Y-%m')) +
  labs(y='', x='', color='') +
  theme_minimal() + 
  theme(legend.position="bottom",
        legend.text=element_text(size=5))

# plot top 10 repos by commit count
repo_bar_plot = ggplot(repo_commit_count_dt[1:min(10, .N), ], aes(y=N, x=project)) +
  geom_bar(stat='identity', fill='black') +
  coord_flip() +
  labs(y='Commit Count', x='') +
  theme_minimal()
```

#### Times of Commits (top 20 repos)

```{r echo=FALSE, fig.align='center'}
date_time_plot
```

*****

#### Most Popular Repos by Commit Count

```{r echo=FALSE, fig.align='center', fig.width=6}
repo_bar_plot
```

*****

#### Most Popular Words in Commit Messages

```{r include=FALSE}
# parse commit messages using spacyr
spacy_initialize()
commit_token_dt = spacy_parse(commit_dt$message)
setDT(commit_token_dt)

# agg by lemma and count
token_count_dt = commit_token_dt[, .N, by=lemma][order(-N),]
# rm stopwords and tokens that don't contain alpha chars and long words
token_count_dt = token_count_dt[!(lemma %in% tm::stopwords('SMART')) &
                                  gsub('[^[:alpha:]]', '', lemma) != '' & 
                                  nchar(lemma) <= 20, ]

# plot top 100 as wordcloud
wordcloud_dt = token_count_dt[1:100,]
wc_plot = tagcloud(wordcloud_dt$lemma, wordcloud_dt$N)

# plot top 10 as bars
barplot_dt = token_count_dt[1:10,]
# change lemma to factor for ordering bars
barplot_dt[, lemma := factor(lemma, rev(lemma))]

token_bar_plot = ggplot(barplot_dt, aes(y=N, x=lemma)) +
  geom_bar(stat='identity', fill='black') +
  coord_flip() +
  labs(y='Count', x='') +
  theme_minimal()
```

```{r results='asis', echo=FALSE, out.extra=''}
cat("<table class='container'><tr>")
cat("<td>")
plot(wc_plot)
cat("</td>")
cat("<td>")
token_bar_plot
cat("</td>")
cat("</tr></table>")
```

*****

#### Commit Log

```{r echo=FALSE, message=FALSE, warning=FALSE}
# dispay git log as DT
display_dt = commit_dt[, .(project, timestamp, message)]
setnames(display_dt, c("Project", "Time", "Commit Message"))
DT::datatable(display_dt)
```

******
